package com.naggi.springboot.lazyinit.data;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

// Generated 2015/07/07 12:06:42 by Hibernate Tools 4.3.1

/**
 * Content generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "content_detail")
public class ContentDetail implements java.io.Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  @Id
  private Long detailId;
  
  
  private String detailName;
  private int price;
  
  @ManyToOne
  private Content content;
  
  @Version
  private Long version;
  private String createdFunction;
  private String updatedFunction;
  
  @CreatedDate
  @DateTimeFormat(iso = ISO.DATE)
  private java.sql.Timestamp createdDate;
  @LastModifiedDate
  @DateTimeFormat(iso = ISO.DATE)
  private java.sql.Timestamp updatedDate;
  @CreatedBy
  private String createdBy;
  @LastModifiedBy
  private String updatedBy;

  private Boolean deleteFlag;


}
