package com.naggi.springboot.lazyinit.data;

// default package
// Generated 2015/08/20 19:15:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MstRoleGroup generated by hbm2java
 */
public class MstRoleGroup implements java.io.Serializable {


  private int roleGroupId;
  private String roleGroupName;
  private Boolean deleteFlag;
  private Date updatedDate;
  private Date createdDate;
  private Integer createdUser;
  private Integer updatedUser;

  public MstRoleGroup() {}


  public MstRoleGroup(int roleGroupId) {
    this.roleGroupId = roleGroupId;
  }

  public MstRoleGroup(int roleGroupId, String roleGroupName, Boolean deleteFlag, Date updatedDate,
      Date createdDate, Integer createdUser, Integer updatedUser) {
    this.roleGroupId = roleGroupId;
    this.roleGroupName = roleGroupName;
    this.deleteFlag = deleteFlag;
    this.updatedDate = updatedDate;
    this.createdDate = createdDate;
    this.createdUser = createdUser;
    this.updatedUser = updatedUser;
  }

  public int getRoleGroupId() {
    return this.roleGroupId;
  }

  public void setRoleGroupId(int roleGroupId) {
    this.roleGroupId = roleGroupId;
  }

  public String getRoleGroupName() {
    return this.roleGroupName;
  }

  public void setRoleGroupName(String roleGroupName) {
    this.roleGroupName = roleGroupName;
  }

  public Boolean getDeleteFlag() {
    return this.deleteFlag;
  }

  public void setDeleteFlag(Boolean deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  public Date getUpdatedDate() {
    return this.updatedDate;
  }

  public void setUpdatedDate(Date updatedDate) {
    this.updatedDate = updatedDate;
  }

  public Date getCreatedDate() {
    return this.createdDate;
  }

  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  public Integer getCreatedUser() {
    return this.createdUser;
  }

  public void setCreatedUser(Integer createdUser) {
    this.createdUser = createdUser;
  }

  public Integer getUpdatedUser() {
    return this.updatedUser;
  }

  public void setUpdatedUser(Integer updatedUser) {
    this.updatedUser = updatedUser;
  }



}
