package com.naggi.springboot.lazyinit.data;
// default package
// Generated 2015/08/20 19:15:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {


  private String roleid;
  private String rolename;
  private Boolean deleteflag;
  private Date updateddate;
  private Date createddate;
  private Long createduser;
  private Long updateduser;

  public Role() {}


  public Role(String roleid) {
    this.roleid = roleid;
  }

  public Role(String roleid, String rolename, Boolean deleteflag, Date updateddate,
      Date createddate, Long createduser, Long updateduser) {
    this.roleid = roleid;
    this.rolename = rolename;
    this.deleteflag = deleteflag;
    this.updateddate = updateddate;
    this.createddate = createddate;
    this.createduser = createduser;
    this.updateduser = updateduser;
  }

  public String getRoleid() {
    return this.roleid;
  }

  public void setRoleid(String roleid) {
    this.roleid = roleid;
  }

  public String getRolename() {
    return this.rolename;
  }

  public void setRolename(String rolename) {
    this.rolename = rolename;
  }

  public Boolean getDeleteflag() {
    return this.deleteflag;
  }

  public void setDeleteflag(Boolean deleteflag) {
    this.deleteflag = deleteflag;
  }

  public Date getUpdateddate() {
    return this.updateddate;
  }

  public void setUpdateddate(Date updateddate) {
    this.updateddate = updateddate;
  }

  public Date getCreateddate() {
    return this.createddate;
  }

  public void setCreateddate(Date createddate) {
    this.createddate = createddate;
  }

  public Long getCreateduser() {
    return this.createduser;
  }

  public void setCreateduser(Long createduser) {
    this.createduser = createduser;
  }

  public Long getUpdateduser() {
    return this.updateduser;
  }

  public void setUpdateduser(Long updateduser) {
    this.updateduser = updateduser;
  }



}
