package com.naggi.springboot.lazyinit.inittest.data;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

// Generated 2015/07/07 12:06:42 by Hibernate Tools 4.3.1

/**
 * ItemType generated by hbm2java
 */
@Data
@Entity
public class MstItemType implements java.io.Serializable {
  @Id
  private int itemTypeId;
  private String itemTypeName;
  private Boolean deleteFlag;

  public MstItemType() {}

  public MstItemType(int itemTypeId) {
    this.itemTypeId = itemTypeId;
  }

  public MstItemType(int itemTypeId, Boolean deleteFlag, String itemTypeName) {
    this.itemTypeId = itemTypeId;
    this.deleteFlag = deleteFlag;
    this.itemTypeName = itemTypeName;
  }


}
