package com.naggi.springboot.lazyinit.inittest.data;
// default package
// Generated 2015/08/20 19:15:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserRoleGroup generated by hbm2java
 */
public class UserRoleGroup implements java.io.Serializable {


  private int userRoleGroupId;
  private String userId;
  private Integer roleGroupId;
  private Boolean deleteFlag;
  private Date updatedDate;
  private Date createdDate;
  private Integer createdUser;
  private Integer updatedUser;

  public UserRoleGroup() {}


  public UserRoleGroup(int userRoleGroupId) {
    this.userRoleGroupId = userRoleGroupId;
  }

  public UserRoleGroup(int userRoleGroupId, String userId, Integer roleGroupId, Boolean deleteFlag,
      Date updatedDate, Date createdDate, Integer createdUser, Integer updatedUser) {
    this.userRoleGroupId = userRoleGroupId;
    this.userId = userId;
    this.roleGroupId = roleGroupId;
    this.deleteFlag = deleteFlag;
    this.updatedDate = updatedDate;
    this.createdDate = createdDate;
    this.createdUser = createdUser;
    this.updatedUser = updatedUser;
  }

  public int getUserRoleGroupId() {
    return this.userRoleGroupId;
  }

  public void setUserRoleGroupId(int userRoleGroupId) {
    this.userRoleGroupId = userRoleGroupId;
  }

  public String getUserId() {
    return this.userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public Integer getRoleGroupId() {
    return this.roleGroupId;
  }

  public void setRoleGroupId(Integer roleGroupId) {
    this.roleGroupId = roleGroupId;
  }

  public Boolean getDeleteFlag() {
    return this.deleteFlag;
  }

  public void setDeleteFlag(Boolean deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  public Date getUpdatedDate() {
    return this.updatedDate;
  }

  public void setUpdatedDate(Date updatedDate) {
    this.updatedDate = updatedDate;
  }

  public Date getCreatedDate() {
    return this.createdDate;
  }

  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  public Integer getCreatedUser() {
    return this.createdUser;
  }

  public void setCreatedUser(Integer createdUser) {
    this.createdUser = createdUser;
  }

  public Integer getUpdatedUser() {
    return this.updatedUser;
  }

  public void setUpdatedUser(Integer updatedUser) {
    this.updatedUser = updatedUser;
  }



}
